services:
  model_runner:
    build:
      context: model_runner
    networks:
      - backend
      
  backend:
    build: .
    env_file:
      - ./backend/.env
    ports:
      - 8764:8764
    networks:
      - frontend
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build:
      context: frontend
      target: development
    networks:
      - frontend
    ports:
      - 80:5173
    volumes:
      - ./frontend:/project
      - /project/node_modules

networks:
  frontend:
  backend: